language: python
# python versions to use during the tests
python:
    - "3.7"
# command to install dependencies
install:
    - pip install -r requirements.txt
# command to run tests
script:
    - py.test
branches:
  only:
   - master
notifications:
  email:
    recipients:
      - alimzaini@outlook.com
    on_success: always
    on_failure: always